{{- if .Values.configmap.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}
data:
  # file-like keys
  config: |-
{{ .Files.Get "config" | indent 4 }}
{{- end }}